blank_issues_enabled: true
contact_links:
  - name: 📚 Nuxt Gtag Documentation
    url: https://github.com/Zadigo/nuxt-business-details#readme
    about: Check the documentation for usage of Nuxt Gtag
